### ISSUE TITLE
Provide install-jdk.properties matrix

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#125]
Provide `install-jdk.properties` matrix file as suggested two years ago: 

- https://mail.openjdk.java.net/pipermail/web-discuss/2018-May/000533.html

### TODO

- [x] Commit initial `install-jdk.properties` file with JDK 14 and JDK 15-ea mappings
- [x] Use `install-jdk.properties` in https://github.com/sormuras/download-jdk GitHub Action
- [x] Generate `install-jdk.properties` by parsing https://jdk.java.net/ HTML sources
- [x] Use `install-jdk.properties` in `install-jdk.sh` avoid realtime HTML parsing
